// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTheme(arg1) {
  return window['go']['app']['App']['DeleteTheme'](arg1);
}

export function GetAppName() {
  return window['go']['app']['App']['GetAppName']();
}

export function GetAudioDevices() {
  return window['go']['app']['App']['GetAudioDevices']();
}

export function GetBlipType() {
  return window['go']['app']['App']['GetBlipType']();
}

export function GetCurrentThemeName() {
  return window['go']['app']['App']['GetCurrentThemeName']();
}

export function GetLanguage() {
  return window['go']['app']['App']['GetLanguage']();
}

export function GetSelectedDevice() {
  return window['go']['app']['App']['GetSelectedDevice']();
}

export function GetTheme() {
  return window['go']['app']['App']['GetTheme']();
}

export function GetThemes() {
  return window['go']['app']['App']['GetThemes']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function InitTray(arg1) {
  return window['go']['app']['App']['InitTray'](arg1);
}

export function IsOverlayMode() {
  return window['go']['app']['App']['IsOverlayMode']();
}

export function QuitFromTray() {
  return window['go']['app']['App']['QuitFromTray']();
}

export function SetDevice(arg1) {
  return window['go']['app']['App']['SetDevice'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function SetNormalWindow() {
  return window['go']['app']['App']['SetNormalWindow']();
}

export function SetRadarOverlay() {
  return window['go']['app']['App']['SetRadarOverlay']();
}

export function SetTheme(arg1) {
  return window['go']['app']['App']['SetTheme'](arg1);
}

export function ShutdownTray() {
  return window['go']['app']['App']['ShutdownTray']();
}

export function StopRadar() {
  return window['go']['app']['App']['StopRadar']();
}

export function ToggleWindowModeFromTray() {
  return window['go']['app']['App']['ToggleWindowModeFromTray']();
}

export function UpdateOverlayStatus(arg1) {
  return window['go']['app']['App']['UpdateOverlayStatus'](arg1);
}
