// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteTheme(arg1:string):Promise<void>;

export function GetAppName():Promise<string>;

export function GetAudioDevices():Promise<Array<models.DeviceSpeakers>>;

export function GetBlipType():Promise<models.Blip>;

export function GetCurrentThemeName():Promise<string>;

export function GetLanguage():Promise<string>;

export function GetSelectedDevice():Promise<models.DeviceSpeakers>;

export function GetTheme():Promise<models.Theme>;

export function GetThemes():Promise<Array<models.Theme>>;

export function GetVersion():Promise<string>;

export function InitTray(arg1:Array<number>):Promise<void>;

export function IsOverlayMode():Promise<boolean>;

export function QuitFromTray():Promise<void>;

export function SetDevice(arg1:models.DeviceSpeakers):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetNormalWindow():Promise<void>;

export function SetRadarOverlay():Promise<void>;

export function SetTheme(arg1:models.Theme):Promise<void>;

export function ShutdownTray():Promise<void>;

export function StopRadar():Promise<void>;

export function ToggleWindowModeFromTray():Promise<void>;

export function UpdateOverlayStatus(arg1:boolean):Promise<void>;
